"""Build a 2-channel WAV demonstrating the PBX's 2100 Hz tone regenerator.

Left  = the signal we transmitted over RTP.
Right = the same call recorded at the modem's analog port (voice mode +VRX).

Three sections, each a matched TX/RX pair from a single call:
  1. 1500 Hz control - AM survives, carrier unchanged
  2. 2100 Hz          - AM removed
  3. 2095 Hz          - AM removed *and* carrier snapped to 2100 Hz

Caveats, deliberately explicit because the file is evidence:

* Alignment is at the start of each detected tone segment, not sample-exact.
  The modem begins recording part-way into our tone, and in the affected
  sections the received tone is generated by a different oscillator, so no
  phase relationship exists to align to.
* Each channel is normalised per section to the same RMS. The two capture
  points have unrelated absolute gains (our A-law RTP stream vs the modem's
  voice ADC), so channel amplitude carries no meaning. What is comparable is
  the *envelope* - the modulation - and the frequency.
"""
import math, struct, sys, wave
import g711, dsp, amdepth

SR = 8000
SECONDS = 4.0
GAP = 0.5
TARGET_DBFS = -12.0

SECTIONS = [
    ("1500 Hz control", "ref/dual_tx_am1500_m24.raw", "ref/dual_rx_am1500_m24.raw"),
    ("2100 Hz",         "ref/dual_tx_am2100_m24.raw", "ref/dual_rx_am2100_m24.raw"),
    ("2095 Hz -> snap", "ref/dual_tx_am2095_m24.raw", "ref/dual_rx_am2095_m24.raw"),
]

def load(path, pt):
    x = g711.decode(open(path, "rb").read(), pt)
    fc, _ = dsp.dominant(x, 800, 3200, coarse=25, fine=1)
    seg = dsp.find_tone_segment(x, fc)
    y = x[seg[0]:seg[1]] if seg else x
    return y, fc

def fine_freq(y, fc):
    w = y[:min(len(y), 16000)]
    best, bf = -1.0, float(fc)
    q = fc - 9.0
    while q <= fc + 9.0:
        p = dsp.goertzel(w, q)
        if p > best:
            best, bf = p, q
        q += 0.05
    return bf

def norm(y, target_dbfs=TARGET_DBFS):
    r = dsp.rms(y)
    if r <= 0:
        return y
    g = (32768.0 * 10 ** (target_dbfs / 20.0)) / r
    return [max(-32768, min(32767, int(v * g))) for v in y]

def main(out="../testrig/regenerator_demo.wav"):
    n = int(SECONDS * SR)
    gap = [0] * int(GAP * SR)
    left, right = [], []
    print("section layout (left = our RTP TX, right = modem analog port):")
    print("  %-9s %-17s %-22s %-22s" % ("t start", "section", "left (sent)", "right (received)"))
    for label, txp, rxp in SECTIONS:
        t0 = len(left) / float(SR)
        tx, ftx = load(txp, 8)
        rx, frx = load(rxp, 0)
        if len(tx) < n or len(rx) < n:
            print("  section %s too short (%.1f / %.1f s)" % (label, len(tx)/SR, len(rx)/SR))
            return 1
        ftx_f, frx_f = fine_freq(tx, ftx), fine_freq(rx, frx)
        dtx = amdepth.am_depth(tx, carrier=ftx_f)[0]
        drx = amdepth.am_depth(rx, carrier=frx_f)[0]
        left.extend(norm(tx[:n]));  left.extend(gap)
        right.extend(norm(rx[:n])); right.extend(gap)
        print("  %-9.2f %-17s %-22s %-22s"
              % (t0, label,
                 "%.1f Hz, AM %.1f%%" % (ftx_f, 100 * dtx),
                 "%.1f Hz, AM %.2f%%" % (frx_f, 100 * drx)))
    assert len(left) == len(right)
    frames = b"".join(struct.pack("<hh", left[i], right[i]) for i in range(len(left)))
    with wave.open(out, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(frames)
    print("\nwrote %s : %.2f s, 2 ch, 16-bit, %d Hz" % (out, len(left) / float(SR), SR))
    return 0

if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:]))
